#!/usr/bin/env ruby

require 'rss'
require "json"

def addpodcast(filename,url)
  urls = Array.new()
  if File.exist?(filename) then
    File.open(filename,"r") do |file|
      urls =  JSON.parse(file.read)
      urls.push(url)
      urls.uniq!
    end

    File.open(filename,"w") do |file|
      file.puts JSON.dump(urls)
    end

  else
    urls = [url]
    File.open(filename,"w") do |file|
      file.puts  JSON.dump(urls)
    end
  end
end

def viewpodcast(filename)
  urls = Array.new()
  if File.exist?(filename) then
    File.open(filename,"r") do |file|
      urls =  JSON.parse(file.read)
    end
  end

  urls.each_with_index{|podcast , index|
    rss = RSS::Parser.parse(podcast)
    puts "No.#{index+1} ####"
    puts "Title:\t\t" + rss.channel.title
    puts "Description:\t" + rss.channel.description
    puts
  }
print "何番のポッドキャストを聞きますか？(半角数字のみ)："  
  num = gets.chomp
  return urls[num.to_i - 1 ]
end

def viewItems(url)
  rss = RSS::Parser.parse(url)
  rss.items.each_with_index{|item , index|
    puts "No.#{index+1} ####"
    puts "Title:\t\t" + item.title
    puts "Description:\t" + item.description
    puts
  }
print "何番のエピソードを聞きますか？(半角数字のみ)："  
      num = gets.chomp
        return rss.items[num.to_i - 1 ].enclosure.url
end

filename = File.expand_path('~') + "/.Podterm/urls";

if ARGV[0] == nil then
loop{
  url = viewpodcast(filename)
  mp3url = viewItems(url)
  `mplayer #{mp3url}`
}
else
  addpodcast(filename,ARGV[0])
end


