#!/bin/sh
po=$(cd $(dirname $0);pwd)
pod="${po}/Podterm/podterm.rb"
hel="${po}/Podterm/help"

if [  $# == 0 ]; then
	clear
	ruby $pod
	clear
	url=`cat ~/.Podterm/mp3url`
	clear
	cat $hel
	mpv -ao alsa $url
fi
if [  $# == 1 ]; then
	ruby "$pod" "$1"
fi
