#!/bin/sh


if [  $# == 0 ]; then
	clear
	ruby Podterm/podterm.rb 
	clear
	url=`cat ~/.Podterm/mp3url`
	clear
	cat Podterm/help
	mpv -ao alsa $url
fi
if [  $# == 1 ]; then
	ruby Podterm/podterm.rb "$1"
fi
