#!/bin/sh
po=$(cd $(dirname $0);pwd)
pod="${po}/podterm/podterm.rb"
hel="${po}/podterm/help"

if [  $# == 0 ]; then
	#clear
	ruby $pod
	#clear
	if [  -e ~/.Podterm/audioUrl ]; then
		url=`cat ~/.Podterm/audioUrl`
		#clear
		cat $hel
		#mpv  $url
		mpv $url

	fi
fi
if [  $# == 1 ]; then
	ruby "$pod" "$1"
fi
